---
osx:
  brew:
    packages:
      - ack
      - ansible
      - autojump
      - cowsay
      - fish
      - fortune
      - gpg2
      - rbenv
      - reattach-to-user-namespace
      - ruby-build
      - macvim
      - pinentry-mac
      - terminal-notifier
      - tmux

    casks:
      - 1password
      - alfred
      - dash
      - docker-toolbox
      - fantastical
      - firefox
      - google-chrome
      - karabiner-elements
      - marked
      - slack
      - spotify
      - vagrant
      - virtualbox
      - vlc

  dotfiles:
    links:
      - src: tmux/tmux.conf
        dest: ~/.tmux.conf
      - src: fish
        dest: ~/.config/fish
      - src: git/gitconfig
        dest: ~/.gitconfig
      - src: git/gitignore
        dest: ~/.gitignore
      - src: pry/pryrc
        dest: ~/.pryrc
