---
macos:
  brew:
    taps:
      - homebrew/cask-fonts

    packages:
      - ack
      - ansible
      - autojump
      - awscli
      - bat
      - boot-clj
      - cowsay
      - elixir
      - entr
      - fd
      - fish
      - fortune
      - gpg2
      - hub
      - jq
      - kops
      - kubectl
      - lynx
      - neovim
      - nvm
      - pass
      - pass-otp
      - rbenv
      - reattach-to-user-namespace
      - ripgrep
      - ruby-build
      - macvim
      - pinentry-mac
      - postgresql
      - telnet
      - terminal-notifier
      - terraform
      - tflint
      - tmux
      - vault
      - watch

    casks:
      - 1password
      - 1password-cli
      - adoptopenjdk
      - alfred
      - aws-vault
      - dash
      - docker
      - fantastical
      - firefox
      - font-fira-code
      - font-ibm-plex
      - font-meslo-for-powerline
      - font-meslo-lg
      - front
      - google-chrome
      - karabiner-elements
      - kitty
      - marked
      - minikube
      - postman
      - robo-3t
      - slack
      - spotify
      - transmission
      - vagrant
      - virtualbox
      - vlc
