---
- name: brew tap casks
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ macos.brew.taps | flatten(levels=1) }}"

- name: warn if skipping updates
  debug:
    msg: not updating brew and upgrading packages; run with BREW_UPGRADE=true
  when: lookup('env', 'BREW_UPGRADE') | bool is false

- name: brew update
  homebrew: update_homebrew=yes
  when: lookup('env', 'BREW_UPGRADE') | bool

- name: brew upgrade
  homebrew: update_homebrew=yes upgrade_all=yes
  when: lookup('env', 'BREW_UPGRADE') | bool

- name: brew install common casks
  homebrew_cask: name={{ macos.brew.casks }} state=installed

- name: brew install common packages
  homebrew: name={{ macos.brew.packages }} state=installed

- name: brew install personal packages
  when: personal_machine
  homebrew: name={{ item }} state=installed
  loop:
    - alot
    - msmtp
    - neomutt
    - notmuch
    - offlineimap
    - w3m

- name: brew install personal casks
  when: personal_machine
  homebrew_cask: name={{ item }} state=installed
  loop:
    - protonmail-bridge
