---
- name: brew tap casks
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ macos.brew.taps | flatten(levels=1) }}"

- name: brew update
  homebrew: update_homebrew=yes

- name: brew upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew install common casks
  homebrew_cask: name={{ macos.brew.casks }} state=installed

- name: brew install common packages
  homebrew: name={{ macos.brew.packages }} state=installed

- name: brew install personal packages
  when: personal_machine
  homebrew: name={{ item }} state=installed
  loop:
    - alot
    - neomutt
    - notmuch
    - offlineimap
    - w3m

- name: brew install personal casks
  when: personal_machine
  homebrew_cask: name={{ item }} state=installed
  loop:
    - protonmail-bridge
