---
- name: clone emacs configuration
  git:
    repo: https://gist.github.com/e90e8e8b1437586fba3f.git
    dest: ~/.emacs.d

- name: clone vim configuration
  git:
    repo: git@github.com:alloy-d/vim-config.git
    dest: ~/.vim
    recursive: yes

- name: create temporary directory for vim
  file:
    dest: ~/.vim-tmp
    state: directory

- name: link vim configs
  file:
    src: "~/.vim/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: vimrc
      dest: ~/.vimrc

- name: update dotfiles
  git:
    repo: git@github.com:alloy-d/dotfiles.git
    dest: ~/.dotfiles.d
    recursive: yes

- name: ensure ~/.config existence
  file:
    dest: ~/.config
    state: directory

- name: symlink dotfiles
  file:
    src: "~/.dotfiles.d/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ macos.dotfiles.links|flatten(levels=1) }}"

- name: create gnupg directory
  file:
    mode: 0700
    state: directory
    path: ~/.gnupg

- name: copy gnupg configs
  copy:
    mode: 0600
    src: "~/.dotfiles.d/gnupg/{{ item }}"
    remote_src: yes
    dest: "~/.gnupg/{{ item }}"
    force: no
    follow: no
    local_follow: no
  loop:
    - gpg.conf
    - gpg-agent.conf
