---
- name: brew update
  homebrew: update_homebrew=yes

- name: brew upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew install common packages
  homebrew: name={{ osx.brew.packages }} state=upgraded

- name: brew install common casks
  homebrew_cask: name={{ item }} state=installed
  loop: "{{ osx.brew.casks | flatten(levels=1) }}"
