---
- name: "create gnupg directory"
  file:
    mode: 0700
    state: directory
    path: ~/.gnupg

- name: "create ~/.gnupg/gpg-agent.conf"
  file:
    mode: 0600
    state: touch
    path: ~/.gnupg/gpg-agent.conf

- name: "configure pinentry program for GPG"
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    regexp: '^pinentry-program '
    state: present
    line: 'pinentry-program /usr/local/bin/pinentry-mac'
